AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*.rb
    - spec/**/*.rb
    - gemirro.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
Naming/FileName:
  Exclude:
    - Rakefile
ModuleLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
