AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*.rb
    - spec/**/*.rb
    - gemirro.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
ModuleLength:
  Exclude:
    - lib/**/*
    - spec/**/*
MethodLength:
  Exclude:
    - lib/**/*
ClassLength:
  Exclude:
    - lib/**/*
ParameterLists:
  Exclude:
    - lib/**/*
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/**/*
Metrics/PerceivedComplexity:
  Exclude:
    - lib/**/*
Metrics/AbcSize:
  Exclude:
    - lib/**/*
Metrics/BlockLength:
  Exclude:
    - lib/**/*
    - spec/**/*
